#!/bin/sh /etc/rc.common

# enables the correct bitbanged spi and i2c device 

#define RIOT_GPIO_MIXER_SPI_SS		26
#define RIOT_GPIO_MIXER_SPI_SCK		11
#define RIOT_GPIO_MIXER_SPI_MOSI	27
#define RIOT_GPIO_MIXER_SPI_MISO	8
#define RIOT_UNUSED	0

#define RIOT_GPIO_LEDBOARD_1_SCK		22
#define RIOT_GPIO_LEDBOARD_2_SDA		23
#define RIOT_GPIO_LEDBOARD_3_GPIO		24

START=60

start() {
	. /lib/ar71xx.sh
	ar71xx_board_detect
	case $AR71XX_BOARD_NAME in
	albatross)
#<id>,<sck>,<mosi>,<miso>,<mode1>,<maxfreq1>,<cs1>,...  
		# insmod spi-gpio-custom bus0=1,11,27,8,0,125000,26 - we're using bit banging 
#<id>,<sda>,<scl>,<udelay>,<timeout>,<sda_od>,<scl_od>,<scl_oo>
		insmod i2c-gpio-custom bus0=0,23,22
		;;
	esac
}


